// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeletePassword():Promise<void>;

export function GetConfig():Promise<main.Config>;

export function GetIP():Promise<string>;

export function GetPassword():Promise<string>;

export function GetUsername():Promise<string>;

export function OpenX(arg1:string):Promise<void>;

export function SetConfig(arg1:string,arg2:string):Promise<void>;

export function SetPassword(arg1:string):Promise<void>;
