// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetIP() {
  return window['go']['main']['App']['GetIP']();
}

export function GetPassword() {
  return window['go']['main']['App']['GetPassword']();
}

export function GetUsername() {
  return window['go']['main']['App']['GetUsername']();
}

export function OpenX(arg1) {
  return window['go']['main']['App']['OpenX'](arg1);
}

export function SetIP(arg1) {
  return window['go']['main']['App']['SetIP'](arg1);
}

export function SetPassword(arg1) {
  return window['go']['main']['App']['SetPassword'](arg1);
}

export function SetUsername(arg1) {
  return window['go']['main']['App']['SetUsername'](arg1);
}
