// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetIP() {
  return window['go']['main']['App']['GetIP']();
}

export function GetPassword() {
  return window['go']['main']['App']['GetPassword']();
}

export function GetUsername() {
  return window['go']['main']['App']['GetUsername']();
}

export function OpenX(arg1) {
  return window['go']['main']['App']['OpenX'](arg1);
}

export function SetConfig(arg1, arg2) {
  return window['go']['main']['App']['SetConfig'](arg1, arg2);
}

export function SetPassword(arg1) {
  return window['go']['main']['App']['SetPassword'](arg1);
}
