// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetIP():Promise<string>;

export function GetPassword():Promise<string>;

export function GetUsername():Promise<string>;

export function OpenX(arg1:string):Promise<void>;

export function SetIP(arg1:string):Promise<void>;

export function SetPassword(arg1:string):Promise<void>;

export function SetUsername(arg1:string):Promise<void>;
